# Generated by Django 6.1.1 on 2026-10-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mobile_num', models.IntegerField()),
                ('vechile_colour', models.CharField(max_length=20)),
                ('Service_no', models.IntegerField()),
                ('Service_mode', models.CharField(max_length=20)),
                ('Amountbill_no', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
